// React/src/DataCell.js
import React from 'react';
import Utils from './utils.js';

export default function DataCell(props) {
  const { startDate, endDate } = props.itemData;
  const isHoliday = Utils.isHoliday(startDate, endDate);
  const isDinner = Utils.isDinner(startDate, endDate);
  const cssClasses = [];
  let text;

  if(isHoliday) {
    cssClasses.push('holiday');
    text = Utils.getHoliday(startDate, endDate).name;
  } else if(isDinner) {
    cssClasses.push('dinner');
    text = 'Dinner Time';
  }

  return (
    <div className={cssClasses}>
      {text}
    </div>
  );
}

// Vue/src/components/DataCell.vue
<template>
  <div :class="markDataCell(cellData)">
    {{ getCellName(cellData) }}
  </div>
</template>
<script>
import Utils from ".././utils.js";

export default {
  props: {
    cellData: {
      type: Object,
      default: () => {},
    },
  },
  methods: {
    markDataCell(cellData) {
      const startDate = cellData.startDate;
      const endDate = cellData.endDate;
      const isHoliday = Utils.isHoliday(startDate, endDate);
      const isDinner = Utils.isDinner(startDate, endDate);

      return {
        holiday: isHoliday,
        dinner: isDinner,
      };
    },
    getCellName({ startDate, endDate, text }) {
      const isHoliday = Utils.isHoliday(startDate, endDate);
      const isDinner = Utils.isDinner(startDate, endDate);

      if (isHoliday) {
        return Utils.getHoliday(startDate, endDate).name;
      } else if (isDinner) {
        return "Dinner Time";
      }

      return text;
    },
  },
};
</script>
